# Generated by Django 4.2.30 on 2026-04-29 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_auditlog"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="role",
            field=models.CharField(
                choices=[("ADMIN", "管理员"), ("MEMBER", "成员")],
                default="MEMBER",
                max_length=16,
                verbose_name="团队角色",
            ),
        ),
    ]
