# Generated by Django 4.2.30 on 2026-04-29 13:44

from django.db import migrations, models
from django.db.models import Q


def normalize_team_admins(apps, schema_editor):
    UserProfile = apps.get_model("users", "UserProfile")

    teams = (
        UserProfile.objects.values_list("team_id", flat=True)
        .distinct()
    )
    for team_id in teams:
        profiles = (
            UserProfile.objects.filter(team_id=team_id)
            .select_related("user")
            .order_by("user__date_joined", "user_id")
        )
        admin_profiles = list(profiles.filter(role="ADMIN"))
        if not admin_profiles:
            first = profiles.first()
            if first:
                first.role = "ADMIN"
                first.save(update_fields=["role"])
            continue

        keep_id = admin_profiles[0].id
        (
            UserProfile.objects.filter(team_id=team_id, role="ADMIN")
            .exclude(id=keep_id)
            .update(role="MEMBER")
        )


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_userprofile_role"),
    ]

    operations = [
        migrations.RunPython(normalize_team_admins, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name="userprofile",
            constraint=models.UniqueConstraint(
                fields=("team",),
                condition=Q(role="ADMIN"),
                name="unique_team_admin",
            ),
        ),
    ]
