# Generated by Django 4.2.30 on 2026-04-29 13:52

from django.db import migrations, models
import django.db.models.deletion


def backfill_team_admin_user(apps, schema_editor):
    Team = apps.get_model("users", "Team")
    UserProfile = apps.get_model("users", "UserProfile")

    teams = Team.objects.all()
    for team in teams:
        if team.admin_user_id:
            continue
        profiles = (
            UserProfile.objects.filter(team_id=team.id)
            .select_related("user")
            .order_by("user__date_joined", "user_id")
        )
        first_profile = profiles.first()
        if not first_profile:
            continue
        team.admin_user_id = first_profile.user_id
        team.save(update_fields=["admin_user"])

        if first_profile.role != "ADMIN":
            first_profile.role = "ADMIN"
            first_profile.save(update_fields=["role"])
        profiles.exclude(id=first_profile.id).update(role="MEMBER")


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_unique_team_admin"),
    ]

    operations = [
        migrations.AddField(
            model_name="team",
            name="admin_user",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="admin_team",
                to="auth.user",
                verbose_name="管理员",
            ),
        ),
        migrations.RunPython(backfill_team_admin_user, migrations.RunPython.noop),
    ]

