# Generated by Django 4.2.30 on 2026-04-29 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0006_team_admin_user"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="userprofile",
            name="unique_team_admin",
        ),
    ]
